#!/bin/bash

# Gyrfalcon (n = 28)
# Filter Max Missingness

# Filter for QUAL (Phred) of 30, already filtered max missingness of 0.1, DP of 5 

vcftools --gzvcf GYRF_HuLiu_RENAMED_VarOnly_DP5_MaxMis0.1.vcf.gz \
    --minQ 30 \
    --recode --recode-INFO-all \
    --stdout | bgzip > GYRF_HuLiu_RENAMED_VarOnly_DP5_MaxMis0.1_Qual30.vcf.gz
    
bcftools index GYRF_HuLiu_RENAMED_VarOnly_DP5_MaxMis0.1_Qual30.vcf.gz
