#!/bin/bash

# Peregrine Falcon ONLY
# TRIMMING FOR NOVASEQ (--nextera --2coulour 30)
# --nextera looks for nextera adapter
# --2colour 30 trims poly G tail and trims ends for quality of at least 30

rawdata=~/scratch/Peregrine/Genomes/Raw_Reads/NovaSeq/
datadir=~/scratch/Peregrine/Genomes/Trimmed_Reads/NovaSeq/

# Trim files with TrimGalore v. 0.6.6 before alignment - change parameters based on results
for file in "${rawdata}"*_1.fastq.gz
do
       base=$(basename ${file} _1.fastq.gz)
       ~/miniforge3/bin/trim_galore --path_to_cutadapt ~/miniforge3/bin/cutadapt --paired --nextera --2colour 30 ${file} ${rawdata}${base}_2.fastq.gz -o ${datadir} --basename ${base}
done
wait
echo "done trimming"
