#!/bin/bash
# Sort (samtools) and Index
# Hu et al. 2022 Gyrfalcon genomes

# Sort

cd ~/scratch/Gyrfalcon/Resequenced_Genomes/BAM_Files

for sample in *
do samtools sort -T ../Sorted_BAM/$sample -o ../Sorted_BAM/$sample $sample
done

### 6. Index BAM files

cd ~/scratch/Gyrfalcon/Resequenced_Genomes/Sorted_BAM

for sample in *.bam; do
  echo "Indexing $sample..."
  samtools index -b "$sample"
done
