#!/bin/bash

# Gyrfalcon (n = 28)
# Filter Max Missingness

# Filter for max missingness of 0.9, DP of 5 already filtered
# sites with missingness GREATER than 0.1 were removed


vcftools --gzvcf GYRF_HuLiu_RENAMED_VarOnly_DP5.vcf.gz \
         --max-missing 0.9 \
         --recode --recode-INFO-all \
         --stdout | bgzip > GYRF_HuLiu_RENAMED_VarOnly_DP5_MaxMis0.1.vcf.gz
    
bcftools index GYRF_HuLiu_RENAMED_VarOnly_DP5_MaxMis0.1.vcf.gz
